### ISSUE TITLE
新版手机端访问不能显示背景图片

### ISSUE THREAD

**Issue by mdddj** [0x2E/Material-T#30]

**Comment by invom** [comment]
默认的图片我放到 imgur 上了，国内访问可能比较慢。

**Comment by gsl6** [comment]
请教个问题，背景图PC端能正常显示，手机端只能显示一部分，这个是我哪里设置出错了

**Comment by 0x2E** [comment]
> 
> 
> 请教个问题，背景图PC端能正常显示，手机端只能显示一部分，这个是我哪里设置出错了

@gsl6 咋都找到这么早的 issue 了 😂 
背景图会根据屏幕尺寸自动调整大小，你不可能让电脑上全屏全图显示的图片放到竖屏手机上还能全屏全图显示呀
