### ISSUE TITLE
代码布局和评论系统

### ISSUE THREAD

**Issue by Acidwits** [0x2E/Material-T#32]
- 代码部分有点奇怪，窗口窄一点，代码长一点的话，会戳出来，想知道pfish.xyz中的代码部分怎么设置？
我文章中的代码部分![1.png](https://i.loli.net/2019/03/24/5c96d3203f6b9.png)那个三个行号的问题已经解决了。
- 给博客添加livere评论系统参照了网上各种教程，都没成功XDD，该如何安装？

**Comment by 0x2E** [comment]
你好 @Acidwits ，
你用的是 v0.9 吧？代码块超出的问题之前已经修复了，`hexo clean` 之后再 `hexo g`试试。

Material-T没有原生支持 livere，你可以在 `layout/_partial/comments/` 里新建一个 `livere.ejs` 文件，将官方给的那一段 js 代码复制进去，然后在主题配置文件里将评论 type 设置为 livere。

最后，建议升级到经过重构的 v1.0 版本，v0.9 已经没有维护计划了。

**Comment by Acidwits** [comment]
刚升级到v1.0，但是代码块还是超出
![1.png](https://i.loli.net/2019/03/31/5ca06762019b8.png)
![2.png](https://i.loli.net/2019/03/31/5ca067620c94b.png)

**Comment by Acidwits** [comment]
评论系统安装好了，没想到这么简单，十分感谢

**Comment by 0x2E** [comment]
>2. 修改 Hexo 的_config.yml
> ```yml
> // 关闭默认代码高亮
> highlight:
>   enable: false
>   line_number: false
>   auto_detect: false
>   tab_replace:
> ```

上面这一步完成了吗？

**Comment by Acidwits** [comment]
都OK了，非常感谢:)
