### ISSUE TITLE
窗口较窄或者页面放大时，文章首页缩略图偏移

### ISSUE THREAD

**Issue by Acidwits** [0x2E/Material-T#34]
如图
![2.png](https://i.loli.net/2019/04/28/5cc56b1b07e23.png)
![1.png](https://i.loli.net/2019/04/28/5cc56b1b1c34a.png)
![3.png](https://i.loli.net/2019/04/28/5cc56b1b1c3a0.png)

**Comment by 0x2E** [comment]
感谢反馈，今天晚些时候会修复。
