### ISSUE TITLE
你好，文章的封面图片怎么设置？

### ISSUE THREAD

**Issue by Xiamao12138** [0x2E/Material-T#36]
你好，文章的封面图片怎么设置？

**Comment by 0x2E** [comment]
你好，在文章页的 Front Matter 中配置 index_img 属性即可。（[文档](https://0x2e.github.io/Material-T-docs/common/#%E9%A6%96%E9%A1%B5%E7%95%A5%E7%BC%A9%E5%9B%BE)）

**Comment by Xiamao12138** [comment]
好的谢谢
