### ISSUE TITLE
归档页面出了点问题

### ISSUE THREAD

**Issue by Acidwits** [0x2E/Material-T#37]
如图
![Snipaste_2019-05-26_17-54-10.png](https://i.loli.net/2019/05/26/5cea62ae6c22964995.png)

不知道是哪里搞错了
点开一个tag时会向下滑动一段
页面在[这](http://acidwits.xyz/archives)

**Comment by 0x2E** [comment]
原版主题没法复现这个情况，看下是不是你魔改导致的问题

**Comment by Acidwits** [comment]
暂时找不到问题所在
不过换了v0.9的archive
感觉也挺好的

tag带空格时（比如`hello world`）好像不会显示tag下的内同

**Comment by Acidwits** [comment]
还有就是草稿中的tag也会被显示出来，但是该tag下不会列出文章
v0.9 v1.0都是如此
![Snipaste_2019-05-29_17-54-20.png](https://i.loli.net/2019/05/29/5cee56e877b0688474.png)

**Comment by 0x2E** [comment]
感谢反馈，草稿和带空格的 tag 显示问题已修复。
