### ISSUE TITLE
Post中粗体不能正常显示

### ISSUE THREAD

**Issue by kongjune** [0x2E/Material-T#40]
博文中使用Markdown实现粗体（双\*包围）不能被正常被显示。

**Comment by 0x2E** [comment]
我试了下是正常的呀

![eYuUp9.png](https://s2.ax1x.com/2019/07/31/eYuUp9.png)

**Comment by kongjune** [comment]
> 我试了下是正常的呀
> 
> ![eYuUp9.png](https://camo.githubusercontent.com/e6e808f606f0f811c1748531102ddba1cc745226/68747470733a2f2f73322e617831782e636f6d2f323031392f30372f33312f6559755570392e706e67)

感谢回复，在更改了Markdown引擎后解决了这个问题。可能是我后期装的插件出现了冲突问题。
