### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by newhans** [0x2E/Material-T#44]
INFO  Files loaded in 371 ms
ERROR /home/newhans/hexo/themes/Material-T/layout/about.ejs:13
    11| </div>
    12| <div class="mt-5 markdown-body">
 >> 13|   <%- insertAbout() %>
    14| </div>

ENOENT: no such file or directory, open 'themes/Material-T/about.md'

**Comment by 0x2E** [comment]
你好，主题目录下有个 about.md，about 页中自定义部分是根据这个文件的内容渲染的，你看下文件是不是被删掉了

**Comment by newhans** [comment]
你好，about.md还在

**Comment by 0x2E** [comment]
`hexo clean` 之后再 `hexo g` 试试

**Comment by newhans** [comment]
感谢你的帮助，have a nice day
