### ISSUE TITLE
关于该Hexo主题的一点建议

### ISSUE THREAD

**Issue by MaverickNone** [0x2E/Material-T#46]
1. 可以加入category的功能，我自己用的时候觉得tag的功能始终有限
2. 可以加入search的功能，一点tag多了，tag本身反倒意义不大了，难以寻找，可以考虑支持一下Next主题使用的 hexo-generator-search 和 hexo-generator-searchdb 本地插件来生成搜索框
3. 这个主题我感觉是我用过的UX最好的，但是很遗憾的是功能还是有限，虽然我没法提供更多帮助，那就只能喊666帮你们加油了![image](https://user-images.githubusercontent.com/38276635/62719753-47c4eb80-b9ce-11e9-98bb-33b8ebc30812.png)

**Comment by 0x2E** [comment]
感谢支持和建议 😃  1、2 的功能正在规划中

**Comment by Darius18** [comment]
> 感谢支持和建议 😃 1、2 的功能正在规划中

加油呀！！！！！

**Comment by 0x2E** [comment]
都完事辣 #57
