### ISSUE TITLE
文章的封面图片始终显示不出来

### ISSUE THREAD

**Issue by MaverickNone** [0x2E/Material-T#48]
我尝试过了设置index_img，但是无论是设置相对路径（我本以为是我自己写的url格式有问题，但是看了很多文章和百科后，尝试了很多次后还是没法显示，我猜可能<a>标签的css出了问题），还是我把图上传到图床后再添加链接，都无法显示。而且博主你自己的博客的首页文章封面图片也没法正常显示。最后我还想问一下，在文章中嵌入图片要怎么处理？和封面一样？还是要用插件什么的？

**Comment by zkqiang** [comment]
![image](https://user-images.githubusercontent.com/32983588/62748144-1578c400-ba8a-11e9-95b0-f8eefc742512.png)

这边显示没问题，你设置应该没问题，可能是网络等其他原因

**Comment by 0x2E** [comment]
@MaverickNone 你好，你说的是这个图片吗
![1.png](https://i.loli.net/2019/08/09/EJdpMAj53IbTFke.png)

昨晚我调整了一下博客的目录，忘记在文章里改了 😂 

文章中的 `index_img` 属性是有效的，你看下是不是 yml 的格式出错了，键和值之间要间隔一个英文空格。

文章正文中嵌入图片就是用正常的 Markdown 或 HTML 语法即可。
```markdown
// Markdown
![your_img_alt_text](your_img_url)
```
```html
// HTML
<img src="your_img_url" alt="your_img_alt_text">
```

**Comment by MaverickNone** [comment]
谢谢！已经成功了，估计是yml哪个地方写错了。。。

**Comment by Martinxux** [comment]
我也是的，文章里面的正常显示，就只有封面图片显示不出来，最开始都显示不出来，查了好多资料现在就只剩封面了。blog.haloa.top
