### ISSUE TITLE
"关于"页始终是空白

### ISSUE THREAD

**Issue by gearhere** [0x2E/Material-T#49]
**在本地无法打开，推到GitHub后点击about则显示一片空白。**

我的操作流程如下：

1）跟随配置教程进行初始化`hexo new page about`，然后得到文件及路径如下：
**...\blog\source\about\index.md**
此文件是否必须生成在Material-T的source下？我做了这个尝试，但没有什么变化；

2）修改index.md如下：
```
---
title: about
date: 2019-08-09 06:03:20
type: "about"
---
```
这一步不知对属性的添加是否正确，此外我在hexo文档中没有找到type这一属性，不知是否有错？

3) 在 **...\blog\themes\Material-T\pages** 下的about.md中加了个一级标题，此处about.md的位置与_config.yml中写明的 **/Material-T/about.md** 又不相同，不知是否是此处的问题？

4）git bash:
```
hexo clear
hexo g
hexo d
hexo s
```
然后发现无论本地还是远端，均无法看到正常的about页面，github仓库中about文件夹下的index.html亦是一片空白，但archive页面一切正常。

希望得到您的解答，谢谢！

**Comment by zkqiang** [comment]
最新版本不需要 `hexo new page about` 了，也不用设置什么，JS 会自动生成
请检查一下 `../blog/themes/Material-T/pages` 中是否存在 `about.md`（空文件即可，无内容）
然后 `hexo clean`  不是 `clear` 否则无效

**Comment by gearhere** [comment]
clear是typo，实际上是用的clean，一段时间等待后已经自动恢复，生成成功了，十分感谢。
