### ISSUE TITLE
关于文章缩略图

### ISSUE THREAD

**Issue by xdedzl** [0x2E/Material-T#55]
您好，缩略图一直设置无效，我是这么写的，还有什么别的参数需要修改么

title: 【Shader特效】—— 爆炸，沙化
date: 2019-06-03 21:08:48
tags:
    - Shader
categories:
    - Diary
index_image: https://github.com/UnityTech/UIWidgets/blob/master/Documentation~/images/example.png # 略缩图

**Comment by MaverickNone** [comment]
给你个正确示范：

```Markdown
title: '[2019-08-15] 游戏结算'
tags:
  - 每日计划
  - 结算
categories:
  - 游戏人生
toc: true
index_img: 'https://i.loli.net/2019/08/16/6NQR3gIPOc8nb2e.png'
date: 2019-08-15 22:21:25
```

**Comment by MaverickNone** [comment]
@xdedzl 冒号后有空格，而且有些键值对的值最好包含在单引号或者双引号之中

**Comment by xdedzl** [comment]
多谢，现在配置好了，没想到回复的这么快
