### ISSUE TITLE
求个有缘人咕出 “友情链接” 页面啦 =-=

### ISSUE THREAD

**Issue by xtaodada** [0x2E/Material-T#60]
### 这是一个什么样的功能？

专门存放隔壁的大佬们的博客链接

### 这个功能可以干什么？

交换链接 进行PY ...

### 额外描述

求个有缘人啦 =-= 

![](https://cdn.imges.link/images/5fc3a21604d40d260ae44708aab2e0d7.png)

**Comment by 0x2E** [comment]
友情链接其实可以写在关于页面里的

**Comment by xtaodada** [comment]
主要是我想要有图片的那种qaq

![](https://cdn.imges.link/images/615b724f0b8f0b3e0bef8c49dedef302.png)

**Comment by 0x2E** [comment]
其实在 `/Material-T/pages/about.md` 里写 HTML 来自定义就可以 😄
