### ISSUE TITLE
翻页按钮的汉化问题

### ISSUE THREAD

**Issue by yangqihang01** [0x2E/Material-T#61]
作者您好，作为一个小白问一下，每个页面底部的上一页和下一页按钮怎么从英文汉化成中文。主题配置文件里面没有找到

**Comment by 0x2E** [comment]
可以在`layout/_partial/paginator.ejs`中修改。

**Comment by 0x2E** [comment]
下个版本会支持 i18n。

**Comment by 0x2E** [comment]
已支持 i18n，修改 Hexo 配置文件中的 `language` 为 `zh-Hans` 或 `en` ，重新生成博客即可生效。
