### ISSUE TITLE
关于搜索的BUG

### ISSUE THREAD

**Issue by yangqihang01** [0x2E/Material-T#63]
作者您好，我发现了一个BUG，不知道是我配置有问题还是主题本身有问题。

当我首先点击搜索，搜了一篇文章，点进去，在这篇文章的页面再次点击搜索，然后再次搜一篇文章，点进去，就会提示404

**Comment by yangqihang01** [comment]
我在您自己的演示网站上也复现了这个问题

**Comment by 0x2E** [comment]
感谢反馈，今晚就修复~

**Comment by 0x2E** [comment]
已修复 👌
