### ISSUE TITLE
推送到 GitHub Pages 后部分文本会英文化

### ISSUE THREAD

**Issue by huaxianyan** [0x2E/Material-T#66]
之前在 V2EX 上关注了这个主题很久了，最近闲下来发现都迭代到 1.3.0，今天就抽空弄了一下

一切都很满意，但是发现一个问题无法定位及解决：

博客上的「主页」、「标签」、「下一页」之类的文本，在本地调试的时候是中文正常的，但是使用 hexo d 推送到 GitHub Pages 上后就变成英文的了

**Comment by mdddj** [comment]
````

> 

> 

> 

> 

> 

> 

> 

> 

> 

> 

>

**Comment by 0x2E** [comment]
`hexo clean` 之后再 `hexo g && hexo d` 呢。

**Comment by zkqiang** [comment]
之前的 i18n 配置有一些误解，目前统一成 `zh-CN`，请更新 [v1.3.1](https://github.com/0x2E/Material-T/releases/tag/v1.3.1) 并确认根目录 _config 的 language 是否为 `zh-CN`

**Comment by huaxianyan** [comment]
@0x2E 我每次都会先 clean 的
@zkqiang 1.3.1 解决了大部分文本，我随便查了查，主页的 ``下一页`` 还是 ``Next``，其他地方都是中文了

**Comment by zkqiang** [comment]
@huaxianyan 理论上应该不会出现这种情况，可能是页面缓存，可以清理浏览器缓存试下

**Comment by huaxianyan** [comment]
@zkqiang 抱歉，是我的问题，已经没问题了
