### ISSUE TITLE
对于主题的一点点建议

### ISSUE THREAD

**Issue by huaxianyan** [0x2E/Material-T#67]
1. 既然可以让用户自定义摘要，那么摘要也是否可以不限制字数？或者有相关设置？

2. 主题配置文件里加入主题主要静态文件自定义路径的功能，方面我们这种无法备案的用户优化访问速度。

一点点建议，仅供参考。

**Comment by 0x2E** [comment]
感谢建议 😄

**Comment by zkqiang** [comment]
建议 1 主要是受框体高度限制，字数必须有最大限制，参考的是 [36kr](https://36kr.com/information/web_news) 这类的样式
如果有更好的样式参考，欢迎提供一下

**Comment by huaxianyan** [comment]
@zkqiang 我的想法是框体高度又文本量来定，宽度限制不变，这样即使拉长点应该也不会太影响美观？

对前段以及设计一窍不通，只是个人愚见。主要之前 Next 就是这样做的（并且不会合并行），就想当然的提出来了，如果不合适请勿见怪。

**Comment by zkqiang** [comment]
@huaxianyan 没关系，有想法就可以提

这个主题的框体主要是受左侧图片的限制（即使没有图片，也会为了统一而等比高度）
所以和 Next 那种上下图文的方式还不太一样

后续考虑通过其他方式来实现你的想法

**Comment by zkqiang** [comment]
@huaxianyan 你好，关于建议 2 ，我已经实现并提交到 develop 分支
_config 里增加了 source_base_path 可以配置 URL 地址

如果你有时间能否帮忙测试一下

https://github.com/0x2E/Material-T/commit/7af41fad792bd2c3e16e8739b074eacb20aaa175

**Comment by huaxianyan** [comment]
@zkqiang 
``font_1067060_qzomjdt8bmp.css`` 会在路径里插入 ``at.alicdn.com``，实际上没有这个目录
``main.css`` 我在 ``/source/css`` 目录里没找到，只找到一堆 styl 格式的文件
``fa-regular-400.woff2`` ``fa-regular-400.woff`` ``fa-regular-400.ttf`` 这 3 个文件我看请求的 URL 是对的，但是下面的 Referer 指向了 css 目录下的 ``all.min.css``
其他文件都正常加载

**Comment by zkqiang** [comment]
@huaxianyan 你需要把 `根目录/ public/` 里 `js` `lib` `css` 这三个文件夹，上传到你的 CDN 根目录下
不需要上传 `Material-T/source`，因为 public 是最终生成的

**Comment by huaxianyan** [comment]
@zkqiang 但是路径含 ``at.alicdn.com`` 的还是访问不了，路径会被强行插一段

**Comment by zkqiang** [comment]
> @zkqiang 但是路径含 `at.alicdn.com` 的还是访问不了，路径会被强行插一段
看是不是设置成这样
source_base_path: https://at.alicdn.com/

如果还有问题，可否发个外链给我看下

**Comment by huaxianyan** [comment]
@zkqiang 我是用的自己机器测试的，还没传 cdn，修改的 source_base_path 为 ``https://pic.neko7ina.com:7777/source_base/source/``

**Comment by zkqiang** [comment]
@huaxianyan 明白问题了，将 [这一行](https://github.com/0x2E/Material-T/blob/develop/layout/_partial/head.ejs#L24) `css_ex` 修改为 `css` 即可

**Comment by huaxianyan** [comment]
@zkqiang 这个 OK 了，还剩下 3 个我说的那个

> `fa-regular-400.woff2` `fa-regular-400.woff` `fa-regular-400.ttf` 这 3 个文件问题依旧，css 目录下只有个 main.css

**Comment by zkqiang** [comment]
@huaxianyan 
css 目录下只有个 main.css 是对的，其他的 css 都在 lib 目录里
字体这个我再看下

**Comment by zkqiang** [comment]
@huaxianyan 
我回来了，刚忙别的了
请问下 font 文件具体是什么问题，你刚才说的
>Referer 指向了 css 目录下的 all.min.css
这个是正常的，因为 font 的 url 是从 css 里发起的
`url(../webfonts/fa-regular-400.woff2)`

**Comment by huaxianyan** [comment]
@zkqiang 我也不清楚是什么原因，我在 Chrome 里看了看 Headers 是这样的

```
General
  Request URL: https://pic.neko7ina.com:7777/public/lib/font-awesome/webfonts/fa-regular-400.woff2
  Referrer Policy: no-referrer-when-downgrade
Request Headers
  Provisional headers are shown
  DNT: 1
  Origin: http://localhost:4000
  Referer: https://pic.neko7ina.com:7777/public/lib/font-awesome/css/all.min.css?v=5.7.2
  Sec-Fetch-Mode: cors
  User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) 
  Chrome/76.0.3809.132 Safari/537.36
```

**Comment by zkqiang** [comment]
@huaxianyan 这个不会影响使用，Referer 就应该显示如此，font 是 all.min.css 请求的，所以 Referer 也是它

**Comment by huaxianyan** [comment]
@zkqiang 请求的 Status 就是 failed，直接访问地址能下到文件，我不太懂为什么会这样

**Comment by zkqiang** [comment]
@huaxianyan 我猜测应该是 CDN 字体跨域问题了，可以看下 console 里有没有 `No ‘Access-Control-Allow-Origin’` 的报错

**Comment by huaxianyan** [comment]
@zkqiang 我刚才用另外一台电脑测试一下所有的字体都在 console 报错跨域了

**Comment by zkqiang** [comment]
@huaxianyan 如果你 font 也用的是 CDN，那应该需要设置 CDN 跨域，可以搜下阿里云那边怎么设置
类似于：https://wenhairu.com/Tencent-CDN-Access.html

**Comment by huaxianyan** [comment]
@zkqiang 好像又有点问题，我在本地测试是 OK 了，但是 ``hexo d`` 到 GitHub Pages 上时发现所有的静态文件地址前面会被加了个博客域名

可以直接看一下 https://www.neko7ina.com/，里面被重设过 path 的静态文件都被指向到 https://www.neko7ina.com/pic.neko7ina.com:7777/public/XXX 了

**Comment by zkqiang** [comment]
@huaxianyan 
配置前边需要加 http，或者双斜杠：
`source_base_path: http://pic.neko7ina.com:7777`
否则会变成相对路径

**Comment by huaxianyan** [comment]
@zkqiang 配置里是绝对路径，配置是
```
source_base_path: https://pic.neko7ina.com:7777/public/
```

**Comment by zkqiang** [comment]
@huaxianyan 
抱歉，找到问题了，是拼接函数的一个坑（自己疏忽了）
麻烦按最新 [helpers.js](https://github.com/0x2E/Material-T/blob/f5969a4bbdca1a0a095784172b80b9e985317e8f/scripts/helpers.js) 代码

**Comment by huaxianyan** [comment]
@zkqiang 没问题了，感谢
