### ISSUE TITLE
about index.html 0kb

### ISSUE THREAD

**Issue by gearhere** [0x2E/Material-T#68]
version：1.3.0
系统：win10

更新主题后，重新生成的 `\public\about\index.html` 为空。

在之前的版本也出现过这种情况，当时多生成了几次莫名好了，我查询了当时的记录，发现从生成失败到成功，两次deploy隔了不到一个小时，没有什么不同的操作，所以不知道问题出在何处。

在其它使用这个主题的用户的博客里，点入about，我也曾经看到过相同的空白。

我能做些什么来确认这个问题吗？

谢谢。

**Comment by 0x2E** [comment]
暂时没找到问题原因，建议安装最新版的 Hexo 再试一下。

（因为我的博客是用 CI 渲染和推送，每次都是用最新版的 Hexo，渲染关于页没失败过，所以我猜测是 Hexo 的某个旧版本依赖存在问题）

**Comment by zkqiang** [comment]
能否提供下 hexo 的版本
之前有用户反馈过，但是开发者这边一直没遇到过无法复现

解决办法是升级最新 hexo-cli，然后重新 `hexo init`

**Comment by zkqiang** [comment]
我尝试修复了一下，麻烦请手动将 [ develop 分支的 pages.js](https://github.com/0x2E/Material-T/blob/develop/scripts/pages.js) 覆盖到本地，再试一下

**Comment by gearhere** [comment]
> 我尝试修复了一下，麻烦请手动将 [ develop 分支的 pages.js](https://github.com/0x2E/Material-T/blob/develop/scripts/pages.js) 覆盖到本地，再试一下

1. 关于版本：
hexo: 3.9.0
hexo-cli: 2.0.0；

2. 我这里将您提供的pages.js覆盖本地后问题已修复。

十分给力！希望对您确定具体的bug有所帮助！

**Comment by zkqiang** [comment]
感谢帮忙测试，那我先 close 这个 issue，如果你再遇到相同问题可再回复
