### ISSUE TITLE
部分 HTML 标签会导致标题渲染失败

### ISSUE THREAD

**Issue by huaxianyan** [0x2E/Material-T#69]
在正文中使用 ``<center><i>XXXX</i></center>`` 来居中文字，紧接着一行的标题就不生效，直接显示 ``# XXX``。

**Comment by zkqiang** [comment]
能否提供一下具体的 md 示例片段

**Comment by huaxianyan** [comment]
@zkqiang 
我之前修改了文稿，现在改回去发现无法复现了，可能是哪里出了问题
