### ISSUE TITLE
界面问题

### ISSUE THREAD

**Issue by scramblecode** [0x2E/Material-T#71]
## 你好请问这个行号要怎么关闭？
![image](https://user-images.githubusercontent.com/54971536/64411943-ea9d8200-d0c0-11e9-8c97-56d787f17ded.png)

**Comment by 0x2E** [comment]
你好，先按照 README 中『快速开始』提到的步骤关闭 Hexo 默认的代码高亮，然后 `hexo clean`， `hexo g` 。
