### ISSUE TITLE
archive与category图片重复

### ISSUE THREAD

**Issue by asjqkkkk** [0x2E/Material-T#73]
![image](https://user-images.githubusercontent.com/30992818/64484601-4db92100-d247-11e9-8577-e254b2f231d7.png)

修改配置文件的图片引用位置后发现图片显示还是以archive的图片，不知道是否有这个问题

**Comment by 0x2E** [comment]
这个问题之前修复过啦，清空浏览器缓存试试

**Comment by asjqkkkk** [comment]
> 这个问题之前修复过啦，清空浏览器缓存试试


![image](https://user-images.githubusercontent.com/30992818/64484912-8a871700-d24b-11e9-8407-b2c18635c185.png)
清除了
![image](https://user-images.githubusercontent.com/30992818/64484916-94a91580-d24b-11e9-824b-b47253a96594.png)
同时运行了clean，还是不行

**Comment by asjqkkkk** [comment]
对了，我的在哪里可以看到material-T的版本呢？有可能因为我的版本不是最新的

**Comment by zkqiang** [comment]
@asjqkkkk 还没有显示版本的地方，可以下载最新版本，把那两个图片覆盖一下

**Comment by asjqkkkk** [comment]
> @asjqkkkk 还没有显示版本的地方，建议直接下载最新 release 版本覆盖吧（注意备份config）

哈哈，下载最新版本，问题解决啦
